import { Container, Card, Typography } from "@mui/material";
import Head from "next/head";
import React from "react";

export default function About() {
  return (
    <>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ mt: 15, pb: 5 }}>
        <Card className="AboutUs">
          <Typography
            component="h1"
            variant="h2"
            align="center"
            mt={3}
            gutterBottom
          >
            About Us
          </Typography>
          <Container>
            <Card className="Card-Bg">
              <Typography
                component="h1"
                variant="h4"
                style={{ color: "white" }}
                gutterBottom
              >
                Background
              </Typography>
              <Typography
                component="h1"
                variant="h6"
                style={{ color: "white" }}
              >
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
                volutpat est justo, eget consequat neque aliquet a. Nullam
                sodales nisl in mi pretium, in auctor felis molestie. Vivamus
                tincidunt enim a enim mattis gravida. Proin vel urna et lacus
                ullamcorper ornare. Donec ultrices gravida lorem mollis
                volutpat. In semper cursus vestibulum. Cras vestibulum nunc
                mollis lorem rhoncus, vel iaculis lectus facilisis. Proin
                finibus dolor vel dignissim rutrum. Nullam non purus efficitur,
                sollicitudin nisl vitae, efficitur turpis. Vivamus malesuada id
                elit porttitor elementum. In eleifend purus eget sodales
                pellentesque. Quisque ullamcorper condimentum sapien vel tempus.
                Integer ac ligula a turpis vulputate.
              </Typography>

              <Typography
                component="h1"
                variant="h4"
                style={{ color: "red" }}
                gutterBottom
                mt={3}
              >
                Agreement
              </Typography>
              <Typography
                component="h1"
                variant="h6"
                style={{ color: "yellow" }}
                gutterBottom
                mt={3}
              >
                <ul>
                  <li>
                    ใช้งาน 1 Client ต่อ 1 Server เท่านั้น -
                    สามารถใช้งานได้กับเซิฟที่อยู่ในเครื่องเดียวกัน (IP เดียวกัน)
                    - สามารถใช้งานกับ Test Server ได้
                  </li>
                  <li>
                    ห้ามแก้ไขในส่วนที่มีการเข้ารหัสโดยเด็ดขาด
                    แต่ไฟล์จำพวกนี้จะได้รับการยกเว้น อาทิเช่น - Config (ได้แก่
                    config.lua config_sv.lua) - Manifest file (ได้แก่
                    _resource.lua, fxmanifest.lua) - HTML (ได้แก่ ui.html,
                    menu.html) - CSS (ได้แก้ style.css, scotty.css)
                  </li>
                  <li>
                    ห้ามนำผลงานไปขายต่อแบบผิดลิขสิทธิ์หรือแจกจ่ายโดยเด็ดขาด
                    โดยข้อนี้ทางเราจะดำเนินการดังนี้ - ทำการยกเลิก License Key
                    และปิดทุกช่องทางการ Support - ทำการดำเนินการตามกฏหมายตาม
                    พระราชบัญญัติลิขสิทธิ์ ปี พ.ศ. 2537 โดยทีมกฏหมาย บริษัท
                    จีไลออน จำกัด จะเป็นติดต่อและประสานงานในส่วนนี้
                  </li>
                  <li>
                    ไม่รับคืนเงินจากการ สั่งซื้อ และ เติมเหรียญ ในทุกกรณี -
                    ก่อนทำการ เติมเหรียญ
                    กรุณาเช็คว่าต้องการเหรียญเท่าไรในการซื้อสคริปจากทางเรา -
                    กรุณาอ่านรายละเอียดของสคริป
                    ว่าทำงานได้อย่างที่ต้องการหรือเปล่าก่อนทำการสั่งซื้อ
                  </li>
                  <li>
                    การรับ Support
                    จะรับกับแค่เจ้าของบัญชีแต่เพียงผู้เดียวเท่านั้น -
                    การนัดรับการ Support แบบ Remote Desktop
                    จะต้องแจ้งล่วงหน้าอย่างน้อย 3 วัน
                  </li>
                  <li>
                    ทุกสคริปสามารถทำงานได้ดีบน es_extended 1.1-1.2 เท่านั้น -
                    หากนอกเหนือจากนี้บางอย่างอาจใช้งานไม่ได้และทางผู้ซื้อจะต้องจัดการเองโดยเราจะคอยให้คำแนะนำเล็กน้อย
                  </li>
                  <li>
                    สามารถเปลี่ยน Password (รหัสผ่าน) ได้ผ่าน Support
                    เพจแต่คุณจะไม่สามารถเปลี่ยนสิ่งต่อไปนี้ได้ - Email (อีเมล์)
                    - Username (ชื่อผู้ใช้งาน) - Full Name
                    (ชื่อจริงที่ได้ทำการลงทะเบียนไว้) - Phone Number
                    (เบอร์โทรศัพท์) * ทางเราจะมีค่าธรรมเนียมในการเปลี่ยนรหัส 150
                    THB
                  </li>
                  <li>
                    ผู้ซื้อสามารถเปลี่ยน IP Address ในการใช้งานได้ทุกๆ 1 วัน
                  </li>
                  <li>
                    ห้ามทำการขาย Account, License Key
                    โดยเด็ดขาดหากพบเห็นจะทำการยกเลิก Account นั้นโดยทันที
                    (และจะไม่ได้รับการ Support ใดๆทั้งสิ้น)
                  </li>
                </ul>
              </Typography>
            </Card>
          </Container>
        </Card>
      </Container>
    </>
  );
}
