// Components
import React from "react";
import Head from 'next/head'
import {
  Card,
  Container,
  Grid,
  Typography,
  CardContent,
  CardActions,
  Button,
} from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import { createTheme, ThemeProvider } from "@mui/material/styles";

// Contents
import { ActivityData } from "@/Data/Data";
import Image from "next/image";

const theme = createTheme();

export default function Shop() {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <main>
          <Container sx={{ pt: 15, pb: 5 }} mt={10}>
            <Card p={5} sx={{ pt: 5 }}>
              <Typography
                component="h1"
                variant="h3"
                align="center"
                gutterBottom
                mt={3}
              >
                Product
              </Typography>

              <Container sx={{ pb: 5 }}>
                <Card className="Card-Bg">
                  <Grid container spacing={4} p={5}>
                    {ActivityData.map((item) => (
                      <Grid item key={item} md={4}>
                        <Card
                          sx={{
                            height: "100%",
                            display: "flex",
                            flexDirection: "column",
                          }}
                          className="hover-zoom"
                        >
                          <Image
                            src={item.src}
                            width={320}
                            height={220}
                            alt="random"
                          />
                          <CardContent sx={{ flexGrow: 1 }}>
                            <Typography
                              gutterBottom
                              variant="h5"
                              component="h2"
                            >
                              {item.title}
                            </Typography>
                            <Typography className="text-indent">
                              {item.contents}
                            </Typography>
                          </CardContent>
                          <CardActions>
                            <Button size="small">View</Button>
                            <Button size="small">Buy</Button>
                          </CardActions>
                        </Card>
                      </Grid>
                    ))}
                  </Grid>
                </Card>
              </Container>
            </Card>
          </Container>
        </main>
        {/* Footer */}
        {/* End footer */}
      </ThemeProvider>
    </>
  );
}
